create TABLE IF NOT EXISTS subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscriber_id BIGINT,
    subscribed_id BIGINT,
    created TIMESTAMP WITHOUT TIME ZONE,
    UNIQUE(subscriber_id, subscribed_id)
);